import type { Metadata } from "next";

import "../globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
  params: { lng },
}: {
  children: JSX.Element;
  params: {
    lng: string;
  };
}) {
  return (
    <html>
      <body
        style={{
          fontFamily: "Inter, sans-serif",
        }}
      >
        {children}
      </body>
    </html>
  );
}
